version: '2' # ecs-cli only support version 1 and 2
services:
  nginx:
    image: nginx:alpine
    volumes:
      - "/mnt/efs/wordpress/current/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      # - "/mnt/efs/wordpress/current/etc/ssl:/etc/ssl"
      - /mnt/efs/wordpress/current/wp-app:/var/www/html # Full wordpress project
      - "/mnt/efs/wordpress/current/etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
    cpu_shares: 100
    mem_limit: 524288000
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=${NGINX_HOST}
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - wordpress
  wordpress:
    image: wordpress:4.9.6-php7.2-fpm-alpine # https://hub.docker.com/_/wordpress/
    ports:
      - 9000:9000 # change ip if required
    volumes:
      - /mnt/efs/wordpress/current/etc/php/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - /mnt/efs/wordpress/current/wp-app:/var/www/html # Full wordpress project
      - /mnt/efs/wordpress/current/src/plugins/test/:/var/www/html/wp-content/plugins/test # Plugin development
      #- /mnt/efs/wordpress/current/theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    depends_on:
      - db
